# Design Ref: MTU-N35 Design
# Plan SC: FR-N35.3
apiVersion: v2
name: minio
description: SaaS Platform minio subchart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
