# api-gateway ExternalSecret
# Design Ref: MTU-N66.design.md §1
# Plan SC: FR-N66.3
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: saas
  labels:
    app.kubernetes.io/part-of: saas-platform
    app.kubernetes.io/component: api-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: SecretStore
  target:
    name: api-gateway-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RATE_LIMIT_CONFIG
      remoteRef:
        key: api-gateway-master
        property: RATE_LIMIT_CONFIG
    - secretKey: API_KEY_SALT
      remoteRef:
        key: api-gateway-master
        property: API_KEY_SALT
