// 보안 위협 인텔리전스 통합 -- FR-N306.1~FR-N306.6
// Design Ref: MTU-N306 DESIGN §1~§6
// Plan SC: SC-1 (IOC매칭 90%+), SC-2 (위협탐지~대응 5분), SC-3 (오탐 10%), SC-4 (감사 100%)
// CSAP: D-06 감사 로그, D-08 접근통제

// -- 타입 정의 ────────────────────────────────────────────────────────────────

/** IOC 타입 */
export type IOCType = 'ip' | 'domain' | 'url' | 'file_hash' | 'email';

/** IOC (Indicator of Compromise) */
export interface IOCIndicator {
  readonly iocId: string;
  readonly type: IOCType;
  readonly value: string;
  readonly threatLevel: 'critical' | 'high' | 'medium' | 'low';
  readonly source: string;
  readonly firstSeen: string;
  readonly lastSeen: string;
  readonly tags: string[];
  readonly confidence: number; // 0~100
}

/** 위협 매칭 결과 */
export interface ThreatMatch {
  readonly matchId: string;
  readonly tenantId: string;
  readonly iocId: string;
  readonly matchedValue: string;
  readonly matchSource: 'firewall_log' | 'access_log' | 'dns_log' | 'email_log';
  readonly severity: 'critical' | 'high' | 'medium' | 'low';
  readonly timestamp: string;
}

/** 차단 정책 */
export interface BlockPolicy {
  readonly policyId: string;
  readonly tenantId: string;
  readonly iocType: IOCType;
  readonly value: string;
  readonly action: 'block' | 'alert' | 'quarantine';
  readonly autoGenerated: boolean;
  readonly createdAt: string;
  readonly expiresAt: string;
}

/** 위협 리포트 */
export interface ThreatIntelReport {
  readonly reportId: string;
  readonly tenantId: string;
  readonly period: string;
  readonly totalIOCs: number;
  readonly matchedThreats: number;
  readonly blockedThreats: number;
  readonly topThreatSources: Array<{ source: string; count: number }>;
  readonly topIOCTypes: Array<{ type: IOCType; count: number }>;
  readonly generatedAt: string;
}

/** 감사 로그 */
export interface ThreatAuditEntry {
  readonly timestamp: string;
  readonly actor: string;
  readonly tenantId: string;
  readonly action: string;
  readonly target: string;
  readonly details: Record<string, unknown>;
}

// -- 감사 로그 ────────────────────────────────────────────────────────────────

const auditLog: ThreatAuditEntry[] = [];

function recordAudit(entry: Omit<ThreatAuditEntry, 'timestamp'>): void {
  auditLog.push({ ...entry, timestamp: new Date().toISOString() });
}

export function getThreatAuditLog(tenantId: string): readonly ThreatAuditEntry[] {
  return auditLog.filter(e => e.tenantId === tenantId);
}

// -- IOC 피드 수집 ────────────────────────────────────────────────────────────

const iocStore: Map<string, IOCIndicator[]> = new Map();

/** IOC 피드 수집 -- FR-N306.1 */
export function ingestIOCFeed(
  tenantId: string,
  indicators: Array<{ type: IOCType; value: string; threatLevel: IOCIndicator['threatLevel']; source: string; tags?: string[] }>,
): IOCIndicator[] {
  const ingested: IOCIndicator[] = [];
  const now = new Date().toISOString();

  for (const ind of indicators) {
    const ioc: IOCIndicator = {
      iocId: `ioc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      type: ind.type,
      value: ind.value,
      threatLevel: ind.threatLevel,
      source: ind.source,
      firstSeen: now,
      lastSeen: now,
      tags: ind.tags ?? [],
      confidence: ind.threatLevel === 'critical' ? 95 : ind.threatLevel === 'high' ? 85 : 70,
    };
    ingested.push(ioc);
  }

  const existing = iocStore.get(tenantId) ?? [];
  existing.push(...ingested);
  iocStore.set(tenantId, existing);

  recordAudit({
    actor: 'system',
    tenantId,
    action: 'IOC_FEED_INGESTED',
    target: tenantId,
    details: { indicatorsIngested: ingested.length },
  });

  return ingested;
}

/** IOC 목록 조회 */
export function getIOCs(tenantId: string): readonly IOCIndicator[] {
  return iocStore.get(tenantId) ?? [];
}

// -- STIX/TAXII 파싱 ──────────────────────────────────────────────────────────

/** STIX/TAXII 데이터 */
export interface STIXBundle {
  readonly type: 'bundle';
  readonly id: string;
  readonly objects: Array<{
    type: string;
    pattern?: string;
    name?: string;
    description?: string;
    labels?: string[];
  }>;
}

/** STIX/TAXII 포맷 파싱 -- FR-N306.2 */
export function parseSTIXBundle(
  tenantId: string,
  bundle: STIXBundle,
): IOCIndicator[] {
  const parsed: IOCIndicator[] = [];
  const now = new Date().toISOString();

  for (const obj of bundle.objects) {
    if (obj.type !== 'indicator' || !obj.pattern) continue;

    // STIX 패턴에서 IOC 추출 (간소화)
    let iocType: IOCType = 'ip';
    let iocValue = obj.pattern;

    if (obj.pattern.includes('ipv4-addr')) {
      iocType = 'ip';
      const match = obj.pattern.match(/(\d+\.\d+\.\d+\.\d+)/);
      iocValue = match?.[1] ?? obj.pattern;
    } else if (obj.pattern.includes('domain-name')) {
      iocType = 'domain';
      const match = obj.pattern.match(/'([^']+)'/);
      iocValue = match?.[1] ?? obj.pattern;
    } else if (obj.pattern.includes('file:hashes')) {
      iocType = 'file_hash';
      const match = obj.pattern.match(/'([a-f0-9]{32,64})'/);
      iocValue = match?.[1] ?? obj.pattern;
    }

    parsed.push({
      iocId: `ioc-stix-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      type: iocType,
      value: iocValue,
      threatLevel: obj.labels?.includes('malware') ? 'critical' : 'high',
      source: `STIX:${bundle.id}`,
      firstSeen: now,
      lastSeen: now,
      tags: obj.labels ?? [],
      confidence: 80,
    });
  }

  const existing = iocStore.get(tenantId) ?? [];
  existing.push(...parsed);
  iocStore.set(tenantId, existing);

  recordAudit({
    actor: 'system',
    tenantId,
    action: 'STIX_BUNDLE_PARSED',
    target: bundle.id,
    details: { objectsCount: bundle.objects.length, iocsParsed: parsed.length },
  });

  return parsed;
}

// -- 위협 상관 분석 ──────────────────────────────────────────────────────────

const matchStore: ThreatMatch[] = [];

/** 위협 상관 분석 (로그 매칭) -- FR-N306.3 */
export function correlateThreats(
  tenantId: string,
  logEntries: Array<{ source: ThreatMatch['matchSource']; value: string; timestamp: string }>,
): ThreatMatch[] {
  const iocs = getIOCs(tenantId);
  const matches: ThreatMatch[] = [];

  for (const entry of logEntries) {
    for (const ioc of iocs) {
      if (entry.value.includes(ioc.value)) {
        const match: ThreatMatch = {
          matchId: `match-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          tenantId,
          iocId: ioc.iocId,
          matchedValue: ioc.value,
          matchSource: entry.source,
          severity: ioc.threatLevel,
          timestamp: entry.timestamp,
        };
        matches.push(match);
        matchStore.push(match);
      }
    }
  }

  if (matches.length > 0) {
    recordAudit({
      actor: 'system',
      tenantId,
      action: 'THREATS_CORRELATED',
      target: tenantId,
      details: { logsAnalyzed: logEntries.length, threatsFound: matches.length },
    });
  }

  return matches;
}

// -- 자동 차단 ────────────────────────────────────────────────────────────────

const blockStore: BlockPolicy[] = [];

/** 자동 차단 정책 생성 -- FR-N306.4 */
export function generateBlockPolicy(
  tenantId: string,
  match: ThreatMatch,
): BlockPolicy {
  const iocs = getIOCs(tenantId);
  const ioc = iocs.find(i => i.iocId === match.iocId);

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const policy: BlockPolicy = {
    policyId: `block-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    tenantId,
    iocType: ioc?.type ?? 'ip',
    value: match.matchedValue,
    action: match.severity === 'critical' ? 'block' : match.severity === 'high' ? 'quarantine' : 'alert',
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    expiresAt: expiresAt.toISOString(),
  };

  blockStore.push(policy);

  recordAudit({
    actor: 'system',
    tenantId,
    action: 'BLOCK_POLICY_CREATED',
    target: policy.policyId,
    details: { iocType: policy.iocType, value: policy.value, action: policy.action },
  });

  return policy;
}

// -- 위협 리포트 ──────────────────────────────────────────────────────────────

/** 위협 인텔리전스 리포트 -- FR-N306.5 */
export function generateThreatReport(
  tenantId: string,
  period: string,
): ThreatIntelReport {
  const iocs = getIOCs(tenantId);
  const matches = matchStore.filter(m => m.tenantId === tenantId);
  const blocks = blockStore.filter(b => b.tenantId === tenantId);

  // 소스별 통계
  const sourceCount = new Map<string, number>();
  for (const ioc of iocs) {
    sourceCount.set(ioc.source, (sourceCount.get(ioc.source) ?? 0) + 1);
  }
  const topSources = [...sourceCount.entries()]
    .map(([source, count]) => ({ source, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5);

  // IOC 타입별 통계
  const typeCount = new Map<IOCType, number>();
  for (const ioc of iocs) {
    typeCount.set(ioc.type, (typeCount.get(ioc.type) ?? 0) + 1);
  }
  const topTypes = [...typeCount.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count);

  recordAudit({
    actor: 'system',
    tenantId,
    action: 'THREAT_REPORT_GENERATED',
    target: tenantId,
    details: { period, totalIOCs: iocs.length, matches: matches.length },
  });

  return {
    reportId: `threat-rpt-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    tenantId,
    period,
    totalIOCs: iocs.length,
    matchedThreats: matches.length,
    blockedThreats: blocks.filter(b => b.action === 'block').length,
    topThreatSources: topSources,
    topIOCTypes: topTypes,
    generatedAt: new Date().toISOString(),
  };
}

/** 위협 인텔리전스 서비스 */
export class ThreatIntelligenceService {
  constructor(private readonly tenantId: string) {}

  ingestFeed(indicators: Parameters<typeof ingestIOCFeed>[1]): IOCIndicator[] {
    return ingestIOCFeed(this.tenantId, indicators);
  }

  parseSTIX(bundle: STIXBundle): IOCIndicator[] {
    return parseSTIXBundle(this.tenantId, bundle);
  }

  correlate(logs: Parameters<typeof correlateThreats>[1]): ThreatMatch[] {
    return correlateThreats(this.tenantId, logs);
  }

  block(match: ThreatMatch): BlockPolicy {
    return generateBlockPolicy(this.tenantId, match);
  }

  generateReport(period: string): ThreatIntelReport {
    return generateThreatReport(this.tenantId, period);
  }

  getIOCs(): readonly IOCIndicator[] {
    return getIOCs(this.tenantId);
  }

  getAuditLog(): readonly ThreatAuditEntry[] {
    return getThreatAuditLog(this.tenantId);
  }
}
